const HomeProduct=
[
    {
        id: 1,
        Name: 'product1',
        price: 26,
        images: 'images/product-10.jpg',
        cat:'camera',
        type:'new',
    },
    {
        id: 2,
        Name: 'product2',
        price: 46,
        images: 'images/product-10.jpg',
        cat:'camera',
        type:'new',
    },
    {
        id: 3,
        Name: 'product3',
        price: 46,
        images: 'images/product-1.jpg',
        cat:'headphone',
        type:'featured',
    },
    {
        id: 4,
        Name: 'product4',
        price: 46,
        images: 'images/product-2.jpg',
        cat:'box',
        type:'featured',
    },
    
    {
        id: 5,
        Name: 'product5',
        price: 56,
        images: 'images/product-3.jpg',
        cat:'shirt',
        type:'new',
    },
    {
        id: 6,
        Name: 'product6',
        price: 66,
        images: 'images/product-5.jpg',
        cat:'clock',
        type:'new',
    },
    {
        id: 7,
        Name: 'product7',
        price: 76,
        images: 'images/product-7.jpg',
        cat:'flowerwater',
        type:'featured',
    },
    {
        id: 8,
        Name: 'product8',
        price: 86,
        images: 'images/product-8.jpg',
        cat:'clock',
        type:'new',
    },
    {
        id: 9,
        Name: 'product9',
        price: 96,
        images: 'images/product-9.jpg',
        cat:'clock',
        type:'featured',
    },
    {
        id: 10,
        Name: 'product10',
        price: 106,
        images: 'images/product-10.jpg',
        cat:'camera',
        type:'new',
    },
    {
        id: 11,
        Name: 'product11',
        price: 116,
        images: 'images/product-11.jpg',
        cat:'shoes',
        type:'top',
    },
    {
        id: 12,
        Name: 'product12',
        price: 126,
        images: 'images/product-12.jpg',
        cat:'camera',
        type:'top',
    },
    {
        id: 13,
        Name: 'product13',
        price: 136,
        images: 'images/product-6.jpg',
        cat:'shoes',
        type:'top',
    },
];

export default HomeProduct;